NEXT-10847 - Add basic management of scheduled tasks, closes #104
shopwareBoostDay/platform pull request #165
Opened 2020-09-17 13:50 UTC by felixbrucker

### 1. What does this change do, exactly?
This PR adds a settings module to view, edit and manually run scheduled tasks:

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/5189997/93480146-6a2d7600-f8fd-11ea-9f32-1293db0c80c4.gif)

### 2. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-09-17 14:03 UTC, jleifeld commented
Changelog is missing :)

2020-09-17 14:28 UTC, felixbrucker commented
Yup @jleifeld, just added some last changes as well as the changelog and markd the PR as ready for review

2020-09-17 19:54 UTC, mitelg commented on src/Core/Framework/MessageQueue/ScheduledTask/Exception/ScheduledTaskException.php
> +class ScheduledTaskException extends \Exception
extend from ShopwareHttpException

2020-09-18 07:38 UTC, shyim approved these changes
For PHP is anything okay for me

2020-09-18 08:05 UTC, mitelg requested changes

2020-09-18 08:05 UTC, mitelg commented on src/Core/Framework/MessageQueue/ScheduledTask/Exception/ScheduledTaskNotFoundException.php
> +        parent::__construct(sprintf('No scheduled task found for id %s', $scheduledTaskId), [
we have some kind of templating within the ShopwareHttpException
```suggestion
        parent::__construct('No scheduled task found with ID "{{ scheduledTaskId }}"', [
```
just use the array key of the second parameters you give

2020-09-18 08:05 UTC, mitelg commented on src/Core/Framework/MessageQueue/ScheduledTask/ScheduledTaskService.php
> +        if (!$scheduledTask) {
```suggestion
        if ($scheduledTask === null) {
```

2020-09-18 08:52 UTC, mitelg approved these changes

2020-09-22 07:14 UTC, mitelg commented
someone with JS skills should also have a look here @shopwareBoostDay/shopware-devs

2020-09-22 07:54 UTC, raknison approved these changes
The JS part is okay so far. I have nothing to complain about except that a few tests would be nice :-)

2020-09-22 08:27 UTC, merged