NEXT-7072 - Search for mail templates
shopwareBoostDay/platform pull request #172
Opened 2020-09-17 14:32 UTC by HoelShare

### 1. What does this change do, exactly?
It wasn't possible to search for mail templates in the administration.
Fixes #85 

### 2. Describe each step to reproduce the issue or behaviour.
Go to settings > Email Templates. Try searching for some templates.

### 3. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2020-09-17 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/shopwareBoostDay/platform?pullRequest=172) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/shopwareBoostDay/platform?pullRequest=172) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/shopwareBoostDay/platform?pullRequest=172) it.</sub>

2020-09-17 15:00 UTC, tobiasberge requested changes

2020-09-17 15:00 UTC, tobiasberge commented on src/Administration/Resources/app/administration/src/module/sw-mail-template/page/sw-mail-template-index/index.js
> +           searchTerm: undefined
I would set an empty string here. This is also done by most search implementations inside the admin.

```suggestion
           searchTerm:''
```

2020-09-17 15:00 UTC, tobiasberge commented on src/Administration/Resources/app/administration/src/module/sw-mail-template/component/sw-mail-header-footer-list/index.js
> +        searchTerm: String
Please use the verbose version:

```js
searchTerm: {
  type: String,
  required: false,
  default: ''
},
```

2020-09-17 15:00 UTC, tobiasberge commented on src/Administration/Resources/app/administration/src/module/sw-mail-template/component/sw-mail-header-footer-list/index.js
> +            handler (value) {
ESLint should cause an error here:

```suggestion
            handler(value) {
```

2020-09-17 15:00 UTC, tobiasberge commented on src/Administration/Resources/app/administration/src/module/sw-mail-template/component/sw-mail-template-list/index.js
> +            handler (value) {
```suggestion
            handler(value) {
```

2020-09-17 15:00 UTC, tobiasberge commented on src/Administration/Resources/app/administration/src/module/sw-mail-template/component/sw-mail-template-list/index.js
> +        searchTerm: String
Please use the verbose version:

```js
searchTerm: {
  type: String,
  required: false,
  default: ''
},
```

2020-09-17 15:00 UTC, tobiasberge commented on changelog/_unreleased/2020-09-17-search-for-mail-templates.md
> +*  Added the search term to the search request, for searching mail templates and mail header footer.
Please provide more specific information, for example:

* Added new optional prop `searchTerm` to `sw-mail-header-footer-list/index.js`
* Added new boolean data prop `disableRouteParams` to `sw-mail-header-footer-list/index.js`
* ...

2020-09-22 07:37 UTC, taltholtmann requested changes

2020-09-22 07:37 UTC, taltholtmann commented on src/Administration/Resources/app/administration/src/module/sw-mail-template/page/sw-mail-template-index/index.js
> -const { Component, Mixin } = Shopware;
this is a breaking change. Removing a mixin can also remove props, methods, data and so on. This leads to failures in plugins working with this component.

2020-09-28 07:18 UTC, shyim commented
As this PR is incomplete I will close it. Feel free to create a new one at shopware/platform when you have fixed the comments

2020-09-28 07:18 UTC, closed without merging