NEXT-12345 - Removal of cover in adminstration if last media is deleted
shopwareBoostDay/platform pull request #263
Opened 2021-01-14 14:50 UTC by aragon999

### 1. Why is this change necessary?
If the last media of a product was removed the cover was not automatically removed.

### 2. What does this change do, exactly?
The problem was, that after the removal of the cover it was set again, since the media was not removed before checking if there is a new cover. Therefore the order of the code is changed, which fixes the issue.

### 3. Describe each step to reproduce the issue or behaviour.
Delete all images of a product.

### 4. Please link to the relevant issues (if any).
https://github.com/shopwareBoostDay/platform/issues/208

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-01-14 15:27 UTC, shyim requested changes

2021-01-14 15:27 UTC, shyim commented on src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-media-form/index.js
> -            this.product.media.remove(productMedia.id);
Can you write a simple jest tests?

2021-01-18 09:08 UTC, aragon999 commented on src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-media-form/index.js
> -            this.product.media.remove(productMedia.id);
Will do that :)

2021-01-20 12:37 UTC, pantrtxp commented
Hey @aragon999 

Since we need to start with our internal work to bring the BoostDay contributions into the product we ask you to complete this PR till next Monday (25.01) if you are still interested in solving this. 
Otherwise we have to close this PR coming Monday.

I hope you understand this.

Sunny regards
Shopware

2021-01-25 08:37 UTC, aragon999 commented
Hey @pantrtxp ,

sorry for the delay, but I unfortunately have at the moment no time to investigate the tests further.
I tried something, but apparently I do not understand the test-framework completely, so currently the tests are failing.
As said I also have no time to investigate it further. Sorry.

2021-01-25 08:37 UTC, closed without merging

2021-01-25 09:18 UTC, pantrtxp commented
Nothing to be sorry about @aragon999 
Thank you for your participation :)