NEXT-10679 - Set total after fetching list items
shopwareBoostDay/platform pull request #271
Opened 2021-01-14 17:45 UTC by lacknere

### 1. Why is this change necessary?
To fix some counter issues in the administration settings pages.

### 2. What does this change do, exactly?
Set the value of total after fetching list items.

### 3. Describe each step to reproduce the issue or behaviour.
Go to settings > documents page for example.

### 4. Please link to the relevant issues (if any).
#205 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

2021-01-15 06:41 UTC, jleifeld approved these changes

2021-01-15 06:45 UTC, jleifeld commented on src/Administration/Resources/app/administration/src/module/sw-settings/mixin/sw-settings-list.mixin.js
> +                    this.total = items.length;
`this.total = items.total`

2021-01-15 06:46 UTC, jleifeld requested changes
You need to use the total value from the API otherwise the pagination does not know how many items exists in general

2021-01-15 07:34 UTC, leichteckig commented
There are some warnings by Eslint. Please take a look and address them. :slightly_smiling_face:

2021-01-15 07:38 UTC, mitelg commented
@leichteckig those are not related to this PR :wink: this warnings come up on every PR. maybe @shyim could switch that off, as these are files already in the code and not touched

2021-01-15 12:23 UTC, shyim approved these changes

2021-01-15 12:23 UTC, mitelg approved these changes

2021-01-15 12:24 UTC, mitelg requested changes

2021-01-15 12:24 UTC, mitelg commented on changelog/_unreleased/2021-01-14-set-total-after-fetching-list-items.md
> +*  Setting the value of `total` after fetching list items in `sw-settings-list.mixin.js`
the change log entry does not match our conventions. have a look here https://github.com/shopware/platform/blob/master/adr/2020-08-03-Implement-New-Changelog.md#changelog-entries

2021-01-15 14:21 UTC, mitelg approved these changes

2021-01-16 00:32 UTC, leichteckig commented
If all changes are approved, the PR is fine for me, thus can be merged. 👍 Thank you @lacknere for your contribution! 💙

2021-01-16 07:54 UTC, merged